apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-proxy-deployment
spec:
  selector:
    matchLabels:
      app: fluentd-proxy
  template:
    metadata:
      labels:
        app: fluentd-proxy
    spec:
      containers:
        - name: fluentd
          image: fluent/fluentd:v1.15.3-1.0
          ports:
            - containerPort: 24224
              protocol: TCP
              name: kt-fluentd-1
          volumeMounts:
            - name: config-volume
              mountPath: /fluentd/etc
      volumes:
        - name: config-volume
          hostPath:
            path: config
