apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-proxy-deployment
spec:
  selector:
    matchLabels:
      app: fluentd-proxy
  template:
    metadata:
      labels:
        app: fluentd-proxy
    spec:
      containers:
        - name: fluentd
          image: docker.io/sakusennx/fluentd-sample:latest
          ports:
            - containerPort: 24224
              protocol: TCP
              name: kt-fluentd-1
