apiVersion: v1
data:
  fluent.conf: |
    <source>
      @type forward
    </source>

    <match docker.**>
      @type stdout
    </match>
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: fluentd
  name: fluentd-cm0
